apiVersion: skaffold/v2beta4
kind: Config
metadata:
  name: lidar-indexer
build:
  artifacts:
    - image: nexus-docker-public-hosted.ossim.io/lidar-indexer
      jib: {}
  tagPolicy:
    sha256: {}
deploy:
  helm:
    releases:
      - name: lidar-indexer
        chartPath: chart
