apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    field.cattle.io/publicEndpoints: '[{"addresses":[""],"port":443,"protocol":"HTTPS",
    "serviceName":"lidar:lidar-indexer","ingressName":"lidar:lidar-indexer","hostname":"lidar-indexer.ossim.io","path":"/",
    "allNodes":false}]'
  name:  {{ .Chart.Name }}
  namespace: lidar
spec:
  rules:
    - host: lidar-indexer.ossim.io
      http:
        paths:
          - backend:
              serviceName:  {{ .Chart.Name }}
              servicePort: 8080
            path: /
  tls:
    - hosts:
        - lidar-indexer.ossim.io
      secretName: ssl-certs
status:
  loadBalancer:
    ingress:
      - hostname: aaac6bc42260c4b60a9e580e4febc19f-e69fe95399e829a2.elb.us-east-1.amazonaws.com