---
micronaut:
  application:
    name: lidar-indexer
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      redoc:
        paths: classpath:META-INF/swagger/views/redoc
        mapping: /redoc/**
      rapidoc:
        paths: classpath:META-INF/swagger/views/rapidoc
        mapping: /rapidoc/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
---
datasources:
  default:
    driverClassName: 'org.postgresql.Driver'
    username: ${PGUSER:postgres}
    password: ${PGPASS:password}
    port: 5432
    url: jdbc:postgresql://${PGHOST:localhost}/lidar_db
---

jpa:
  default:
    packages-to-scan:
      - 'lidar.indexer'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
        dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect

---
liquibase:
  datasources:
    default:
      change-log: 'classpath:db/liquibase-changelog.groovy'
---
endpoints:
  liquibase:
    enabled: true
    sensitive: false
---
micronaut:
    server:
        cors:
            enabled: true
        port: 8888

---
#micronaut:
#  io:
#    watch:
#      paths: src/main
#      restart: true
