---
micronaut:
  application:
    name: lidar-indexer

---
datasources:
  default:
    driverClassName: 'org.postgresql.Driver'
    username: ${PGUSER:postgres}
    password: ${PGPASS:password}
    port: 5432
    url: jdbc:postgresql://${PGHOST:localhost}/lidar_db
---

jpa:
  default:
    packages-to-scan:
      - 'lidar.indexer'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
---

liquibase:
  datasources:
    default:
      change-log: 'classpath:db/liquibase-changelog.groovy'
---

endpoints:
  liquibase:
    enabled: true
    sensitive: false
---
micronaut:
    server:
        cors:
            enabled: true

---
#micronaut:
#  io:
#    watch:
#      paths: src/main
#      restart: true
